---
title: "Data Viz Demo"
author: "Sara Colom & Eve Perry"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: kable
    code_folding: hide
---


```{r, message = F, warning = F}
# Read in data & libraries
library(tidyverse)
library(stringr)
library(highcharter)
library(bhhi.doc)

#Download data from `Y:\Research\BHHI\Statewide Survey\state_survey_benchmarking\data`

state <- read_rds("../../state_survey_benchmarking/data/state_cleaned.rds")

source("aesthetics.R")
```



# Scatter plot

```{r}
tibble(x = rnorm(100, mean = 45, sd = 1.5),
       y = x*1.5*rnorm(100, mean = 45, sd = 5)) %>% 
  mutate(group = sample(c("group1", "group2"), replace = T, size = n()),
         color = case_when(group == "group1" ~ bhhi_palette("green"),
                           group == "group2" ~ bhhi_palette("yellow"))) %>% 
  hchart(., 
         type = "scatter", 
         hcaes(x = x, 
               y = y,
               group = group,
               color = color),
         showInLegend = F) %>% 
  hc_add_series(name = "Group 1", color = bhhi_palette("green"), marker = list(symbol = "point")) %>% 
  hc_add_series(name = "Group 2", color = bhhi_palette("yellow"), marker = list(symbol = "point")) 
  
```

# Bar graph

```{r}
state %>% 
  mutate(sheltered = if_else(sheltered == 1, "Sheltered", "Not sheltered")) %>% 
  count(sheltered) %>% 
    hchart(., 
         type = "bar", 
         color = bhhi_palette("yellow", names = FALSE),
         hcaes(x = sheltered, 
               y = n),
         name = "n") %>% 
           hc_xAxis(
           title = ""
         ) %>% 
  hc_yAxis(
    title = list(text = "Count")
  ) %>% 
  hc_title(
    text = "Count of Shelter Status"
  ) %>% 
  hc_caption(text = "Unweighted overall counts are shown.")
```

# Grouped bar graph

```{r}
state %>% 
  mutate(sheltered = if_else(sheltered == 1, "Sheltered", "Not sheltered")) %>% 
  filter(!is.na(veteran_status)) %>% 
  group_by(sheltered, veteran_status) %>% 
  summarise(n = n(),
            .groups = "keep") %>% 
  ungroup() %>% 
  mutate(colors = case_when(veteran_status == 1 ~ bhhi_palette("blue"),
                            veteran_status == 0 ~ bhhi_palette("yellow"))) %>% 
    hchart(., 
         type = "bar",
         hcaes(x = sheltered, 
               y = n,
               group = veteran_status,
               color = colors),
         name = "Veteran status",
         showInLegend = F) %>% 
           hc_xAxis(
           title = ""
         ) %>% 
  hc_add_series(name = "Veteran", color = bhhi_palette("blue"), marker = list(symbol = "line")) %>% 
  hc_add_series(name = "Not veteran", color = bhhi_palette("yellow"), marker = list(symbol = "line")) %>% 
  hc_yAxis(
    title = list(text = "Count")
  ) %>% 
  hc_title(
    text = "Count of Veteran Status by Shelter Status"
  ) %>% 
  hc_caption(text = "Unweighted overall counts are shown.")
```

# Panel style bar plots

```{r}
state <- state %>% 
  mutate(across(matches("female|male"), as.factor)) %>% 
  rename("trans-female" = trans_female,
         "trans-male" = trans_male) 

vars_plot <- c("female", "male", "trans-female", "trans-male")

plot_single_bar <- function(var){
  
  
state %>% 
  count(!!sym(var)) %>% 
    hchart(., 
         type = "bar", 
         color = bhhi_palette("green", names = FALSE),
         hcaes(x = !!sym(var), 
               y = n),
         name = "n") %>% 
           hc_xAxis(
           title = ""
         ) %>% 
  hc_yAxis(
    title = list(text = "Count")
  ) %>% 
  hc_title(
    text = paste("Count of", var)
  ) %>% 
  hc_caption(text = "Unweighted overall counts are shown.")
}

plot_list <- map(vars_plot, plot_single_bar)

hw_grid(plot_list, rowheight = 300) %>%
  htmltools::browsable()

```



# Histogram

```{r}
hchart(state$age_self_report,
       type = "histogram",
       color = bhhi_palette("blue"),
       name = "age", 
       showInLegend = FALSE) %>% 
  hc_title(text = "State Survey Age Distribution") %>% 
  hc_yAxis(title = list(text = "Frequency")) %>% 
  hc_xAxis(title = list(text = "Age")) %>% 
  hc_caption(text = "Unweighted data is shown.")
```

